### PR TITLE
build_conda: remove sysroot directory

### PR DESCRIPTION
**Pull request by kaushikcfd**
Suggested by @matthiasdiener here: https://github.com/inducer/pytato/pull/225#issuecomment-985592892.

### CODE REVIEW

**Review by matthiasdiener — APPROVED** [review]
LGTM, thanks!

**Comment by kaushikcfd** [comment]
See https://github.com/inducer/pytato/pull/226 as a test.

**Review by inducer — APPROVED** [review]
Thanks! I'll wait for the test to pass and merge.

**Comment by inducer** [comment]
Looks good! In it goes.

**Pull request merged**
